version: '3'
services:
  postgres:
    image: postgres:12.6
    container_name: postgres-db
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/postgres_data
    networks:
      - airflow_network

networks:
  airflow_network:
    external:false

volumes:
  postgres_data:
